-- ========================================================
-- ESTIMATE MODULE DATABASE UPDATE FOR LILY INTERIORS
-- Import this file in phpMyAdmin if you already have the main database
-- ========================================================

SET FOREIGN_KEY_CHECKS = 0;

-- Table structure for `app_estimate_catalog`
CREATE TABLE `app_estimate_catalog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(50) NOT NULL,
  `item_name` varchar(150) NOT NULL,
  `specifications` text NOT NULL,
  `unit` varchar(20) NOT NULL DEFAULT 'S.ft',
  `default_rate` decimal(12,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=60 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for `app_estimate_catalog`
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('1', 'Ceiling', 'Plain Particle Ceiling', 'Plain Particle ceiling: Designed decorative fixed ceiling of plain particle Board-Star/super. Thickness: 12mm on BT.garjan wooden frame all complete with matt enamel/plastic paint finish as per design.', 'S.ft', '520.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('2', 'Ceiling', 'Drop Beam Ceiling', 'Drop Beam: Supply fitting/fixing of drop ceiling over 7\'-0\" height plain particle board on garjan wooden frame all complete plastic paint as per design.', 'S.ft', '540.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('3', 'Ceiling', 'Gypsum Ceiling', 'Gypsum Ceiling: Supply fitting/fixing of gypsum ceiling over 8\'-6\" height 24\"x24\" board on garjan wooden frame all complete.', 'S.ft', '80.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('4', 'Ceiling', 'Duco Finish Particle Ceiling', 'Plain Particle ceiling: Designed decorative fixed ceiling of plain particle Board-Star/super. Thickness: 12mm on BT.garjan wooden frame all complete with doccu paint finish.', 'S.ft', '600.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('5', 'Furniture', 'Full Height Wardrobe Cabinet', 'Cabinet: Making, supplying and fixing of full height cabinet made of 18mm HPL pasting board shutter & outer side with inside shelf by 18mm G.ply(Akij) with booth side .5mm waterproof indian formica auto machine pasting on almunium T-Bit bordering and big size groove handrail, made Length VariableX 102\"(H) X16\"/18\"(D) including all accessories matching edging with backside extra damp protection all complete as per design.', 'S.ft', '2150.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('6', 'Furniture', 'Low Height Cabinet (LHC)', 'Low Height Cabinet (LHC): Making, supplying and fixing of LHC cabinet made Length VariableX 30\"(H) X24\"(D) with 18mm melamine / HPL board & matching edging all complete.', 'S.ft', '1700.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('7', 'Furniture', 'Kitchen Overhead Cabinet (OHC)', 'Kitchen (O.H.C): Making, supplying and fixing of kitchen cabinet made of 18mm garjan ply(Akij) with HPL pasting and aluminium profile handle bar made with including all accessories matching edging all complete.', 'S.ft', '2250.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('8', 'Furniture', 'Kitchen Middle Cabinet (MHC)', 'Kitchen (M.H.C): Making, supplying and fixing of kitchen cabinet made of 3/4\" garjan ply(Akij) with HPL sheet pasting and aluminium profile handle bar made with including all accessories matching edging all complete.', 'S.ft', '3100.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('9', 'Furniture', 'Kitchen Lower Cabinet (LHC)', 'Kitchen (L.H.C): Making, supplying and fixing of kitchen cabinet made of 3/4\" marine ply(Akij) with HPL sheet pasting aluminium profile handle bar including all SS accessories matching edging all complete.', 'S.ft', '2850.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('10', 'Furniture', 'Dinner Wagon Cabinet', 'Dinner Wagon: Making, supplying and fixing of dinner wagon cabinet made of 18mm HPL with Akij G.Plywood(main body) & 18mm glass profile (shutter) with shutter front side are mercury glass finishing & middle space design glass on marble top made Length VariableX 96\"(H) X16\"(D) with including all accessories matching edging all complete.', 'S.ft', '2450.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('11', 'Furniture', 'TV Cabinet with Charcoal Finish', 'TV Cabinet: Making, supplying and fixing of TV cabinet made of 18mm HPL with Akij G.ply board on Garjan framing and booth side imported charcoal finishing & including all accessories matching edging all complete as per design.', 'S.ft', '1350.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('12', 'Furniture', 'Dressing Unit with Touch LED Mirror', 'Dressing: Making, supplying and fixing of dressing cabinet for bedroom made of 18mm HPL Pasting Akij Plywood boards and inside shelf by white/gray formica on ahmed g.ply including best quality mirror with touch lighting and imported cabinet glass frame, making best quality dressing stool/seater all complete as per design.', 'S.ft', '1450.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('13', 'Furniture', 'Curtain Pelmet Box', 'Palmet Box & Paneling: Making, supplying and fixing of curtain pelmet box made of 18mm G.Ply(Akij) on BT.Garjan wooden frame with matching edging including all accessories all complete with doccu paint as per design.', 'S.ft', '1050.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('14', 'Furniture', 'King Size Sleeping Bed (5\'-6\"x7\'-0\")', 'Sleeping Bed: Making decorative king size sleeping bed for master bedroom(size:5\'-6\"x7\'-0\") supplying, fixing and made of 18mm Garjan Plywood(Akij) board and Top side & down side are solid wood and original indian fabrics,foaming finishing with Eurasia mattress (10year warranty) including Eurasia mattress topper matching edging complete.', 'nos', '115000.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('15', 'Furniture', 'Modern Reception Table', 'Reception Table: Making, supplying and fixing of modern reception table made Length VariableX 40\"(H) x96\"(L)x18\"D with 18mm HPL board with matching edging all complete accessories.', 'nos', '44000.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('16', 'Furniture', 'Meeting Table 8\' x 3\'', 'Meeting Table: Supply fitting/fixing of meeting table 8\'-0\"x3\'-0\" HPL board with metal leg all complete as per design.', 'nos', '30500.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('17', 'Furniture', 'Workstation 6-Person (Clear Glass Divider)', 'Workstation 6p: Making workstation made Length Variable 32\"X30\"(Height) X24\"(depth) with keyboard tray with upper divider by 10mm clear glass(1FT height) and frosted paper design on lower part 18mm melamine board & matching edging. All complete as per design.', 'per.', '8000.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('18', 'Furniture', 'Workstation 3-Person', 'Workstation 3p: Making workstation table made Length Variable 48\"X30\"(Height) X24\"(depth) with keyboard tray and drawer unit Table Top (HPL) lower part 18mm melamine board & matching edging. All complete as per design.', 'per.', '12500.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('19', 'Furniture', 'Counselor Table (4\'x2\')', 'Counselor Table: Making fitting/fixing of counselor table 4\'-0\"x2\'-0\" HPL board(top) with lower part 18mm melamine board all complete.', 'nos', '12500.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('20', 'Furniture', 'Hanging Common Basin Set', 'Common Basin set: Making, supplying and fixing of Hanging common basin with big size design round mirror & basin top granite (lower part 18mm Akij Marine.Ply with doccu) including all accessories all complete.', 'nos', '42300.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('21', 'Furniture', 'Solid Segun/Chambol Wood Folding Door', 'Folding Door (2 pcs): Making, supplying and fixing of folding door made of ctg segun/teakchambol solid wood with frosted glass and doccu paint frame made Length VariableX 84\"(H) X16\" including all accessories matching edging with all complete as per design.', 'S.ft', '1850.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('22', 'Wall & Floor', '10mm Frameless Tempered Glass Partition', 'Glass Partition: Supply fitting/fixing frameless glass partition made of 10mm thick glass with all hardware/accessories such as stainless steel handles, protector bit and VVP auto-closer,stopper lock etc. All complete as per design.', 'S.ft', '290.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('23', 'Wall & Floor', 'Tempered Glass Door 3\'x7\'', 'Tempered Glass Door: Supply fitting/fixing frameless glass door (size: 3\'-0\"x7\'-0\") made of 10mm thick tempered glass with all hardware/accessories such as stainless steel handles and VVP auto-closer,stopper lock etc. All complete as per design.', 'nos', '11500.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('24', 'Wall & Floor', 'Tempered Glass Door 2\'-6\"x7\'', 'Tempered Glass Door: Supply fitting/fixing frameless glass door (size: 2\'-6\"x7\'-0\") made of 10mm thick tempered glass with all hardware/accessories such as stainless steel handles and VVP auto-closer,stopper lock etc. All complete as per design.', 'nos', '11000.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('25', 'Wall & Floor', 'Wall Partition 12mm Garjan Ply HPL', 'Wall Partition Work: Making, Supplying, Fitting fixing of wall partition 12mm garjan ply board with garjan wood framing and HPL pasting all complete as per design.', 'S.ft', '800.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('26', 'Wall & Floor', 'Wall Paneling / Sofa Back Decoration', 'Wall Decoration (sofa back): Making, supplying and fixing of wall paneling made of 18mm G.Ply(Akij) with matching edging including all accessories all complete with doccu paint as per design.', 'S.ft', '1050.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('27', 'Wall & Floor', 'PVC CNC Bit Cut Wall Paneling', 'Wall Paneling(washroom wall): Making, supplying and fixing of master bedroom toilet side wall paneling made of 18/12mm pvc board CNC bit cutting all complete as per design.', 'S.ft', '460.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('28', 'Wall & Floor', 'Imported Charcoal Louver Paneling', 'Counter Table paneling work: Making, supplying and fixing of kitchen counter / wall paneling made of imported charcoal louver all complete as per design.', 'S.ft', '750.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('29', 'Wall & Floor', 'Imported PVC Floor Carpet', 'PVC Floor Carpet: Supply fitting/ fixing of pvc floor carpet(imported) for lift / kitchen area all complete.', 'S.ft', '165.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('30', 'Wall & Floor', 'Imported Floor Carpet (Rooms)', 'Floor Carpet: Supply fitting/ fixing of floor carpet(imported) all room & common space all complete.', 'S.ft', '107.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('31', 'Wall & Floor', '35mm Green Grass Carpet', 'Veranda Floor Grass Carpet: Supply fitting/ fixing of 35mm green grass floor carpet(imported) all complete.', 'S.ft', '130.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('32', 'Wall & Floor', 'SS Sliding Security Gate', 'SS Security Gate: Supply fitting/fixing of 6\'-2\"x7\'-4\" sliding ss security gate all complete.', 'S.ft', '1050.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('33', 'Paint', 'Berger Plastic Paint (ECE Roller Finish)', 'Plastic paint (roller finish): Plastic paint (Berger/Asian brand) of approved color to on plaster and others surfaces (1coat sealer+2coat putty+2coat ECE) Easy Clean Emulsion finish after necessary sealer, lime putty,cleaning,sand papering the base surfaces as per standard.', 'S.ft', '45.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('34', 'Paint', 'Berger Luxury BEE Paint (Foam Finish)', 'BEE paint (foam finish): Luxury paint (Berger brand) of approved color to on plaster surfaces (1coat sealer+3coat putty+1coat sealer+2coat BEE) Breathe easy Emulsion finish after necessary sealer, lime putty,cleaning,sand papering the base surfaces as per standard.', 'S.ft', '70.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('35', 'Paint', 'Berger Enamel Paint (Window / Grill)', 'Enamel Paint: All bed rooms window & verandah grill enamel paint (Berger brand) of approved color to on metal surfaces (1coat RFLPR+2coat Thinner T-6+2coat RSE) after necessary cleaning,sand papering the base surfaces as per direction.', 'S.ft', '50.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('36', 'Electrical', 'LED Office Hang Light 4FT 72w', 'LED Office Hang Light 72w: Supplying fitting and fixing of complete set of 4FT length LED ceiling Light (Energy+) with all accessories.', 'nos', '2550.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('37', 'Electrical', 'LED Office Hang Light 8FT 120w', 'LED Office Hang Light 120w: Supplying fitting and fixing of complete set of 8FT length LED ceiling Light (Energy+) with all accessories.', 'nos', '5150.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('38', 'Electrical', 'LED Panel Light 12w Round', 'LED Panel Light 12w: Supplying fitting and fixing of LED panel Light (Energy+) with all accessories etc. all complete as per design.', 'nos', '650.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('39', 'Electrical', 'LED Conceal Panel Light 2\'x2\' 48w', 'LED Panel Light 48w: Supplying fitting and fixing of 2\'x2\' LED conceal panel Light (Energy+) with all accessories etc. all complete as per design.', 'nos', '2800.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('40', 'Electrical', 'LED Exclusive 8-Ring Chandelier', 'LED Exclusive hanging Light 8 ring: Supplying fitting and fixing of LED exclusive hanging Light (Energy+) with all accessories etc. all complete as per design.', 'nos', '31240.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('41', 'Electrical', 'Wall Surface Down Spot Light 12w', 'Wall Surface down Spot Light 12w: Supplying fitting and fixing of LED spot Light (Energy+) 12watt with all accessories etc. all complete as per direction.', 'nos', '1790.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('42', 'Electrical', 'Heavy Duty 3-Faces Strip Light', 'Three faces Strip Light: Supply, fitting & fixing imported Heavy duty Energy+ copper strip light with warm color best quality of approved color with all other accessories etc.', 'mtr.', '220.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('43', 'Electrical', 'Heavy Duty Profile Light with Diffuser', 'Profile Light: Supply, fitting & fixing imported Heavy duty profile light best quality of approved color with all other accessories etc.', 'RFT', '255.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('44', 'Electrical', 'BRB BYA Cable 1C x 1.5 rm', 'Electric cabling work (BRB): 1C X 1.5 rm BYA cable.', 'coil', '4800.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('45', 'Electrical', 'BRB BYA Cable 1C x 2.5 rm', 'Electric cabling work (BRB): 1C X 2.5 rm BYA cable.', 'coil', '7659.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('46', 'Electrical', 'BRB BYA Cable 1C x 4.0 rm', 'Electric cabling work (BRB): 1C X 4.0 rm BYA cable.', 'coil', '11923.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('47', 'Electrical', 'MK / ART-DNA 13A/15A Multi Socket', 'M.K / ART-DNA SOCKET (Deluxe/Premium): 13A/15A, multi socket with gang box.', 'nos', '464.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('48', 'Electrical', 'MK / ART-DNA Switch 2-Gang / 3-Gang', 'M.K / ART-DNA SWITCH (Deluxe/Premium): 2-Gang / 3-Gang (1 way) switch.', 'nos', '395.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('49', 'Electrical', 'AC Power Circuit Breaker', 'Circuit Breaker: AC Power circuit breaker.', 'nos', '580.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('50', 'Electrical', 'Full Project Electrical Wiring & Fitting Labor', 'Electric work wiring and fitting charges for full Project (Single Unit).', 'Job', '42000.00', '2026-09-07 12:42:11');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('53', 'Ceiling', 'sdasdas', 'dasdasdasdas', 'S.ft', '45454.00', '2026-09-07 14:20:49');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('54', 'Ceiling', 'sdfsdafasdf', 'sdafasdfsadfasdf', 'S.ft', '54654654.00', '2026-09-07 14:21:23');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('55', 'Ceiling', 'Test Item 1788769572', 'Test specs', 'S.ft', '550.00', '2026-09-07 14:26:12');
INSERT IGNORE INTO `app_estimate_catalog` (`id`, `category`, `item_name`, `specifications`, `unit`, `default_rate`, `created_at`) VALUES ('59', 'Thai Glass', 'aSdsa', 'sadasdasdsd', 'S.ft', '345.00', '2026-09-07 14:58:14');

-- Table structure for `app_estimates`
CREATE TABLE `app_estimates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `estimate_no` varchar(50) NOT NULL,
  `client_name` varchar(150) NOT NULL,
  `client_designation` varchar(100) DEFAULT NULL,
  `client_company` varchar(150) DEFAULT NULL,
  `client_address` text DEFAULT NULL,
  `client_phone` varchar(50) DEFAULT NULL,
  `subject` varchar(255) NOT NULL,
  `project_type` enum('commercial','residential') DEFAULT 'commercial',
  `group_by` enum('category','room') DEFAULT 'category',
  `working_days` varchar(50) DEFAULT '25-30 working days',
  `advance_pct` decimal(5,2) DEFAULT 60.00,
  `running_pct` decimal(5,2) DEFAULT 30.00,
  `final_pct` decimal(5,2) DEFAULT 10.00,
  `total_amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `discount_amount` decimal(14,2) DEFAULT 0.00,
  `grand_total` decimal(14,2) NOT NULL DEFAULT 0.00,
  `status` enum('draft','sent','approved','converted') DEFAULT 'draft',
  `converted_project_id` int(11) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `prepared_by` varchar(100) DEFAULT 'Md. Rukonuzzaman',
  `prepared_by_designation` varchar(100) DEFAULT 'Interior Designer',
  `approved_by` varchar(100) DEFAULT 'Md. Mustafizur Rahman',
  `approved_by_designation` varchar(100) DEFAULT 'Managing Director',
  `created_by` int(11) NOT NULL DEFAULT 1,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `estimate_no` (`estimate_no`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for `app_estimates`
INSERT IGNORE INTO `app_estimates` (`id`, `estimate_no`, `client_name`, `client_designation`, `client_company`, `client_address`, `client_phone`, `subject`, `project_type`, `group_by`, `working_days`, `advance_pct`, `running_pct`, `final_pct`, `total_amount`, `discount_amount`, `grand_total`, `status`, `converted_project_id`, `notes`, `prepared_by`, `prepared_by_designation`, `approved_by`, `approved_by_designation`, `created_by`, `created_at`, `updated_at`) VALUES ('1', 'EST-2025-001', 'Managing Director', '', 'Managing Director', 'Suite-1307, Level-13, Computer City Center (Multiplan Center) New Elephant Road, Dhaka', '', 'Agreement for Commercial Space Interior works (1st floor) At Elephant road Dhaka', 'commercial', 'category', '25-30 working days', '60.00', '30.00', '10.00', '852754.00', '0.00', '852754.00', 'draft', NULL, '', 'Md. Rukonuzzaman', 'Interior Designer', 'Md. Mustafizur Rahman', 'Managing Director', '1', '2025-09-03 10:00:00', '2026-09-07 19:56:49');
INSERT IGNORE INTO `app_estimates` (`id`, `estimate_no`, `client_name`, `client_designation`, `client_company`, `client_address`, `client_phone`, `subject`, `project_type`, `group_by`, `working_days`, `advance_pct`, `running_pct`, `final_pct`, `total_amount`, `discount_amount`, `grand_total`, `status`, `converted_project_id`, `notes`, `prepared_by`, `prepared_by_designation`, `approved_by`, `approved_by_designation`, `created_by`, `created_at`, `updated_at`) VALUES ('13', 'EST-2026-010', 'ফদ্গদসগদফগ', '', 'ফদ্গদসগদফগ', 'দফগদ্গ', '', 'দ্গদস', 'commercial', 'category', '25-30 working days', '60.00', '30.00', '10.00', '1120.00', '0.00', '1120.00', 'draft', NULL, '', 'Md. Rukonuzzaman', 'Interior Designer', 'Md. Mustafizur Rahman', 'Managing Director', '1', '2026-09-07 19:55:18', '2026-09-07 19:58:23');

-- Table structure for `app_estimate_items`
CREATE TABLE `app_estimate_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `estimate_id` int(11) NOT NULL,
  `section_name` varchar(100) NOT NULL,
  `section_order` int(11) NOT NULL DEFAULT 1,
  `sl_no` int(11) NOT NULL DEFAULT 1,
  `description` text NOT NULL,
  `unit` varchar(20) NOT NULL,
  `quantity` decimal(10,2) NOT NULL DEFAULT 0.00,
  `unit_price` decimal(12,2) NOT NULL DEFAULT 0.00,
  `amount` decimal(14,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `estimate_id` (`estimate_id`)
) ENGINE=InnoDB AUTO_INCREMENT=248 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for `app_estimate_items`
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('230', '1', '1. Paint Work', '1', '1', 'Plastic paint (roller finish): Berger/Asian brand Easy Clean Emulsion with sealer & lime putty.', 'S.ft', '2000.00', '45.00', '90000.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('231', '1', '1. Paint Work', '1', '2', 'Luxury BEE Paint (foam finish): Berger Breathe Easy Emulsion luxury finish.', 'S.ft', '766.71', '70.00', '53670.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('232', '1', '1. Paint Work', '1', '3', 'Drop Beam: Supply fitting/fixing of drop ceiling over 7\'-0\" height plain particle board on garjan wooden frame all complete plastic paint as per design.', 'S.ft', '1.00', '540.00', '540.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('233', '1', '1. Paint Work', '1', '4', 'Plain Particle ceiling: Designed decorative fixed ceiling of plain particle Board-Star/super. Thickness: 12mm on BT.garjan wooden frame all complete with doccu paint finish.', 'S.ft', '1.00', '600.00', '600.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('234', '1', '1. Paint Work', '1', '5', 'Drop Beam: Supply fitting/fixing of drop ceiling over 7\'-0\" height plain particle board on garjan wooden frame all complete plastic paint as per design.', 'S.ft', '1.00', '540.00', '540.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('235', '1', '1. Paint Work', '1', '6', 'Plain Particle ceiling: Designed decorative fixed ceiling of plain particle Board-Star/super. Thickness: 12mm on BT.garjan wooden frame all complete with matt enamel/plastic paint finish as per design.', 'S.ft', '1.00', '520.00', '520.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('236', '1', '1. Paint Work', '1', '7', 'Gypsum Ceiling: Supply fitting/fixing of gypsum ceiling over 8\'-6\" height 24\"x24\" board on garjan wooden frame all complete.', 'S.ft', '1.00', '80.00', '80.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('237', '1', '2. Wall & Floor Treatment', '2', '1', '10mm Frameless Tempered Glass Partition with SS hardware & VVP closer.', 'S.ft', '450.00', '290.00', '130500.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('238', '1', '2. Wall & Floor Treatment', '2', '2', 'Tempered Glass Door (3\'x7\') 10mm with VVP auto closer.', 'nos', '4.00', '11500.00', '46000.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('239', '1', '2. Wall & Floor Treatment', '2', '3', 'Imported Floor Carpet all common space.', 'S.ft', '685.42', '107.00', '73340.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('240', '1', '2. Wall & Floor Treatment', '2', '4', 'Gypsum Ceiling: Supply fitting/fixing of gypsum ceiling over 8\'-6\" height 24\"x24\" board on garjan wooden frame all complete.', 'S.ft', '1.00', '80.00', '80.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('241', '1', '2. Wall & Floor Treatment', '2', '5', 'Gypsum Ceiling: Supply fitting/fixing of gypsum ceiling over 8\'-6\" height 24\"x24\" board on garjan wooden frame all complete.', 'S.ft', '1.00', '80.00', '80.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('242', '1', '3. Furniture Work', '3', '1', 'Modern Reception Table made of 18mm HPL board with matching edging.', 'nos', '1.00', '44000.00', '44000.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('243', '1', '3. Furniture Work', '3', '2', 'Meeting Table 8\'x3\' HPL board with metal leg.', 'nos', '1.00', '30500.00', '30500.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('244', '1', '3. Furniture Work', '3', '3', 'Workstation 6-Person with 10mm glass divider & keyboard tray.', 'per.', '6.00', '8000.00', '48000.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('245', '1', '3. Furniture Work', '3', '4', 'Full Height Cabinet with 18mm HPL & Akij G.ply, formica auto pasting.', 'S.ft', '155.49', '2150.00', '334304.00', '2026-09-07 19:56:51');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('246', '13', 'Ceiling', '1', '1', 'Plain Particle ceiling: Designed decorative fixed ceiling of plain particle Board-Star/super. Thickness: 12mm on BT.garjan wooden frame all complete with doccu paint finish.', 'S.ft', '1.00', '600.00', '600.00', '2026-09-07 19:58:23');
INSERT IGNORE INTO `app_estimate_items` (`id`, `estimate_id`, `section_name`, `section_order`, `sl_no`, `description`, `unit`, `quantity`, `unit_price`, `amount`, `created_at`) VALUES ('247', '13', 'Ceiling', '1', '2', 'Plain Particle ceiling: Designed decorative fixed ceiling of plain particle Board-Star/super. Thickness: 12mm on BT.garjan wooden frame all complete with matt enamel/plastic paint finish as per design.', 'S.ft', '1.00', '520.00', '520.00', '2026-09-07 19:58:23');

SET FOREIGN_KEY_CHECKS = 1;
